<table class="table table-dashed table-hover table-condensed ">
				<thead>
					<tr>
						<th>
							STATUS
						</th>
						<th>
							ROOM
						</th>
						<th>
						    FEE
						</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>ACTIVE</td>
						<td>102</td>
						<td>PAYED</td>
					</tr>
				</tbody>
</table>